apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
spec:
  description: "Клонирование репозитория из Git"
  inputs:
    params:
    - name: repo-url
      description: "URL вашего Git-репозитория"
      default: ""
  outputs:
    resources:
    - name: repo
      type: git
      description: "Клонированный репозиторий"
  steps:
  - name: git-clone
    image: alpine/git
    command: ["git"]
    args: ["clone", "{{inputs.params.repo-url}}", "/workspace/repo"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: workspace
    emptyDir: {}
