apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clonebuildpush
spec:
  params:
    - name: REPO
    - name: IMAGE
    - name: TAG
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./terraform-azure/Dockerfile
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: $(params.REPO)
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)"
        - name: FORMAT
          value: "docker"
        - name: CONTEXT
          value: "$(workspaces.source.path)/terraform-azure" 
    - name: kubectl-run
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: script
          value: |
            kubectl apply -f https://github.com/blinovmaksym/terraform_deploy_kuber/blob/main/terraform-azure/init_db.yml
            kubectl get deployment   
