apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone_build_push-run-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: clone_build_push
  podTemplate:
    securityContext:
      fsGroup: 65532  
  params:
    - name: REPO
      value: "https://github.com/blinovmaksym/terraform_deploy_kuber"
    - name: IMAGE
      value: "docker.io/maksymblinov/init_db"
    - name: TAG
      value: test
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi