apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:  
  steps:
  - name: git-clone
    image: alpine/git:v2.26.2
    script: |
      git clone https://github.com/blinovmaksym/terraform_deploy_kuber.git
      cd terraform_deploy_kuber
      cat README.md
 