apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
  - name: repo-url
    type: string
    default: https://github.com/blinovmaksym/terraform_deploy_kuber
  - name: initDbManifest
    type: string
    default: ./source/terraform-azure/init_db.yaml  
  steps:
  - name: git-clone
    image: alpine/git:v2.26.2
    script: |
      git clone $(params.repo-url) ./source
      cd source
      cat README.md
  - name: apply-init-db-manifest
    image: alpine:latest
    script: |
       kubectl apply -f $(params.initDbManifest)
 