apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: git-push-binding
spec:
  params:
  - name: gitrevision
    value: main
  - name: gitrepositoryurl
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: git-push-template
spec:
  params:
    - name: gitrevision
      default: main
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clonebuildpushrun-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: clonebuildpush
        podTemplate:
          securityContext:
            fsGroup: 65532  
        params:
          - name: gitrepositoryurl
            value: "https://github.com/blinovmaksym/terraform_deploy_kuber"
          - name: IMAGE
            value: "docker.io/maksymblinov/init_db"
          - name: TAG
            value: test1
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi   
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-push-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: git-push-trigger
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "pipeline"
            value:
              secretName: github-trigger-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["push"]
      bindings:
        - ref: git-push-binding
      template:
        ref : git-push-template

